### ISSUE TITLE
list of parameters

### ISSUE THREAD

**Issue by felixbur** [rsprouse/klsyn#6]
i couldn't find a list of Klatt parameters in the documentation
I thought this url might provide one
http://linguistics.berkeley.edu/plab/guestwiki/index.php?title=Klatt_Synthesizer_Parameters#Voice_skew_.28vs.29

but when I tried  i get the error for vs
/klsyn/klpfile.py", line 103, in read
    fld)
Exception: Unrecognized varied parameter 'vs'.

**Comment by rsprouse** [comment]
The original documentation by Klatt is in the klsynman.pdf file in the directory containing the C code.

The wiki page you cited summarizes the parameters found in the .pdf, and it contained an error. The 'voice skew' parameter name is 'sk', not 'vs'.

Thanks for the note. The wiki has been updated.
